Add functions to CoolPropLib
CoolProp/CoolProp pull request #2084
Opened 2022-01-31 12:03 UTC by friederikeboehm

### Description of the Change

This PR adds the two functions AbstractState_get_mole_fractions and AbstractState_fluid_names to CoolPropLib. These call the corresponding functions in AbstractState so they can be accessed using the High-Level-Interface.

### Benefits

Adds functionality to the High-Level-Interface.

### Possible Drawbacks

None

### Verification Process

I tested both functions using the Mathematica Wrapper, which also received a thorough update (see PR ...). Both functions returned expected values or expected error messages.

![grafik](https://user-images.githubusercontent.com/84069190/151790402-6eeb1341-7f6e-4f4a-b3c6-1396466aa621.png)

### Applicable Issues

None

2022-01-31 12:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CoolProp/CoolProp?pullRequest=2084) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CoolProp/CoolProp?pullRequest=2084) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CoolProp/CoolProp?pullRequest=2084) it.</sub>

2022-01-31 22:20 UTC, ibell commented
There are some issues that need to be addressed, as I mentioned in my review.  Especially, memory leaks.

2022-01-31 22:25 UTC, ibell requested changes
Please follow coding conventions of other functions in CoolPropLib interface.  No additional allocation, pre-allocated buffers only.

2022-01-31 22:25 UTC, ibell commented on include/CoolPropLib.h
> +    EXPORT_CODE void CONVENTION AbstractState_fluid_names(const long handle, char **& fluids, long *N, long *errcode, char *message_buffer, const long buffer_length);
Please return a delimited string in a pre-allocated buffer passed into the function.  See other examples that return strings in this file.

2022-01-31 22:25 UTC, ibell commented on include/CoolPropLib.h
> +    EXPORT_CODE void CONVENTION AbstractState_get_mole_fractions(const long handle, double *& fractions, long *N, long *errcode, char *message_buffer, const long buffer_length);
fractions should be pre-allocated buffer of given length passed into this function

2022-01-31 22:25 UTC, ibell commented on src/CoolPropLib.cpp
> +        fluids = (char**)malloc(sizeof(char*)**N);                        // fluids is only allocated memory if AbstractState exists for handle --> only needs to be freed, if *N != 0
Memory leak. No low-level memory allocation, please use the string joining functions in CPStrings.h

2022-01-31 22:25 UTC, ibell commented on src/CoolPropLib.cpp
> +            strcpy(fluids[i],_fluids[i].c_str());
This is ok, but please operate on pre-allocated buffer

2022-01-31 22:25 UTC, ibell commented on src/CoolPropLib.cpp
> +        fractions = (double*) malloc(sizeof(double)**N);                        // fractions is only allocated memory if AbstractState exists for handle --> only needs to be freed, if *N != 0
fractions should be pre-allocated by the caller

2022-02-01 15:59 UTC, friederikeboehm commented
Implemented requested changes, hope this is more in line with the other functions 😃

2022-02-02 03:35 UTC, ibell requested changes
Small edits only, should be good to go after they are resolved

2022-02-02 03:35 UTC, ibell commented on include/CoolPropLib.h
> +     * @param fluids '&' delimited list of fluids
It would be better if you used the delimiter from the configuration: http://www.coolprop.org/coolprop/Configuration.html (LIST_STRING_DELIMITER)

2022-02-02 03:35 UTC, ibell commented on src/CoolPropLib.cpp
> +        std::vector<std::string> _fluids = AS->fluid_names();
Use the string join method: https://github.com/CoolProp/CoolProp/blob/339a7ac4977bace36947ef6608b68bc258afdc2c/include/CPstrings.h#L113

2022-02-03 00:04 UTC, ibell approved these changes

2022-02-03 00:04 UTC, merged