implemented TCX Huber-JPCRD-2016 for CO2
CoolProp/CoolProp pull request #2267
Opened 2023-07-21 12:01 UTC by Arnab-Mahanti

### Description of the Change

 This change implements the new thermal conductivity model Huber-JPCRD-2016-CO2 for CO2. This changes the thermal conductivity contributions as follows:
- Dilute contribution: hardcoded `CarbonDioxideHuberJPCRD2016`
- Critical contribution: `simplified_Olchowy_Sengers` with values from Huber 2016
- Residual contribution: `polynomial` with values from Huber 2016 

### Benefits

[The older model from Scalabrin et. al. contains  a non-physical bump near the critical temperature of CO2 even though the density is far away from the critical point. Comparision with [NIST Thermophysical Properties]( https://webbook.nist.gov/chemistry/fluid/) shows this phenomenon to be non-existent.

### Possible Drawbacks

Not known

### Verification Process

Here is a comparison of the three models: CoolProp (current), REFPROP (Actually corresponds to NIST Thermophysical Properties), CoolProp (modified).

![image](https://github.com/CoolProp/CoolProp/assets/64639502/80662722-d638-41b7-b2bb-8ec956be9acd)

### Applicable Issues

``Closes #2265``

2023-07-21 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CoolProp/CoolProp?pullRequest=2267) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CoolProp/CoolProp?pullRequest=2267) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CoolProp/CoolProp?pullRequest=2267) it.</sub>

2023-07-21 13:03 UTC, ibell commented
Thank you very much, this is very nice work. Some small comments in my review before I merge.

2023-07-21 16:14 UTC, Arnab-Mahanti commented
@ibell Have you commented anything? Sorry, I didn't understand what you meant.

2023-07-21 16:15 UTC, ibell requested changes

2023-07-21 16:15 UTC, ibell commented on src/Backends/Helmholtz/TransportRoutines.cpp
>  CoolPropDbl TransportRoutines::conductivity_dilute_hardcoded_CO2(HelmholtzEOSMixtureBackend& HEOS) {
I think it would be good here to leave the original formulation but add a new function

2023-07-21 16:15 UTC, ibell commented on CoolPropBibTeXLibrary.bib
> +	author = {M.L. Huber and E.A. Sykioti and M.J. Assael and  R.A. Perkins},
You need spaces between first initials, otherwise the parsing gets messed up. So it would be M. L. Huber and so on

2023-07-21 16:15 UTC, ibell commented on src/Backends/Helmholtz/TransportRoutines.cpp
>  CoolPropDbl TransportRoutines::conductivity_dilute_hardcoded_CO2(HelmholtzEOSMixtureBackend& HEOS) {
With some additional information in the function name about the reference where it came from

2023-07-21 16:15 UTC, ibell commented
Doh I forgot to close out the review

2023-07-21 17:27 UTC, Arnab-Mahanti commented on src/Backends/Helmholtz/TransportRoutines.cpp
>  CoolPropDbl TransportRoutines::conductivity_dilute_hardcoded_CO2(HelmholtzEOSMixtureBackend& HEOS) {
done

2023-07-21 17:28 UTC, Arnab-Mahanti commented on CoolPropBibTeXLibrary.bib
> +	author = {M.L. Huber and E.A. Sykioti and M.J. Assael and  R.A. Perkins},
Done. 
`Note:` Many others have a similar issue.

2023-07-21 17:33 UTC, Arnab-Mahanti commented
Ah wait. There are some issues with the commits.

2023-07-21 17:54 UTC, Arnab-Mahanti commented
What a mess. I have added the changes. @ibell

2023-07-21 18:04 UTC, ibell commented
Looks good I think. Can you confirm that you get the validation data from the paper with your code after all the changes? It would be best to update the points in the testing too, but that can be after.

2023-07-21 18:05 UTC, ibell approved these changes

2023-07-21 18:05 UTC, ibell commented
Once this is merged, want to tackle the same thing for viscosity? You are a quick study of the CoolProp code

2023-07-21 18:14 UTC, Arnab-Mahanti commented
I will try if I can find some time.

2023-07-21 18:22 UTC, Arnab-Mahanti commented
I guess the viscosity model does not have a major issue for CO2. Following is a comparison at P=8e6.

![image](https://github.com/CoolProp/CoolProp/assets/64639502/040673ec-9e16-4056-866c-48b33d3fd3b0)

2023-07-21 18:58 UTC, ibell commented
No major issue, but it should be more accurate

2023-07-21 18:58 UTC, ibell commented
So the last thing: please confirm you get the validation data in the paper for conductivity model

2023-07-21 20:49 UTC, Arnab-Mahanti commented
### Validation with the reference paper

The following program was used for validation.

```c++
#include <iostream>
#include <CoolProp.h>
#include <matplot/matplot.h>
#include <iomanip>

int main(int argc, char const *argv[])
{
    auto [P, T] = matplot::meshgrid(matplot::linspace(20, 200, 10), matplot::linspace(300, 1100, 9));
    auto k = matplot::transform(P, T, [](auto p, auto t)
                                { return CoolProp::PropsSI("CONDUCTIVITY", "P", p * 1e6, "T", t, "CO2"); });

    for (auto &&row : k)
    {
        for (auto &&i : row)
        {
            std::cout << std::setprecision(4) << i * 1000 << "\t";
        }
        std::cout << "\n";
    }

    return 0;
}
```

The output for the range of `PXT = [20:10:200]X[300:1001100]` is as follows:

![image](https://github.com/CoolProp/CoolProp/assets/64639502/95d2adbe-981a-48d0-a8cc-bf20ee7cf45e)

The values for `[0,0.1]X[240,300:100:1100]` are as follows:
![image](https://github.com/CoolProp/CoolProp/assets/64639502/cbfd30bc-51db-49d2-8ea9-4cb929c2ccfe)

For the values of 0MPa Pressure  Exceptions occur at the `HelmholtzEOSMixtureBackend::post_update` step called from `solver_rho_Tp`. Here is a view of the backtrace of the call stack.

![image](https://github.com/CoolProp/CoolProp/assets/64639502/d32c630c-abce-497e-b9c4-87ddfe91c910)

The values obtained for 240K at P=[20:20:120] are as follows:
165.5   180.2   193.1   204.7   215.5   225.7

2023-07-21 20:52 UTC, Arnab-Mahanti commented
Except for P=0MPa the values are in excellent agreement. A typo has been fixed.

2023-07-22 00:52 UTC, ibell commented
Did you check with the tabulated check values in the paper? There should be like 7 of them

2023-07-22 03:01 UTC, Arnab-Mahanti commented
These values are  from Table 8

2023-07-22 03:18 UTC, Arnab-Mahanti commented
Similar phenomenon at \rho=0. Some problem in the solver of EOS.

![image](https://github.com/CoolProp/CoolProp/assets/64639502/4143ec62-e2ef-4e47-91a5-3f69b2e48123)

For T=310K:
The comparison is done with automatic viscosity estimation only.

![image](https://github.com/CoolProp/CoolProp/assets/64639502/6d73ac99-5bb7-4a88-af6e-3257907bd3da)

Critical enhancement is not implemented empirically, but rather through the simplified crossover model. (Section 3.3).

2023-07-22 11:49 UTC, ibell commented
Right, usually I use a density of 1e-6 or something for the zero densities. Anyhow, thanks for the nice contribution, merging

2023-07-22 11:49 UTC, merged