New C Interface Functions
CoolProp/CoolProp pull request #2317
Opened 2023-11-23 08:20 UTC by CSchulzeTLK

### Description of the Change

A few new C interface functions have been added. They enable accessing some information which is currently not available in the C interface. I guess they were just missing.
I did not yet add docstrings to the headers. I didn't know where to copy the descriptions from (as it surely exists somewhere in the library).

### Benefits

A more complete C interface?

### Possible Drawbacks

Future maintenance?

### Verification Process

We already use this interface in the TILMedia library. So, the interface is ready to use. However, not all failure cases (try/catch) are tested. The interface functions have been duplicated and modified from existing functions in the same file, to meet the same requirements.

2023-11-23 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CoolProp/CoolProp?pullRequest=2317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CoolProp/CoolProp?pullRequest=2317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CoolProp/CoolProp?pullRequest=2317) it.</sub>

2023-11-26 01:11 UTC, ibell commented
Are the integer types handled properly? The C integer types should match the approach in the other exposed functions. For instance I don't think you want ``long long``?  Also, do we really want ``const * const`` rather than ``const *``? I am always confused by that.

2023-11-27 14:00 UTC, jowr commented
Thank you for the contribution. Yes, I think it makes sense to align the variable types. Could you please do that?

2023-11-28 01:58 UTC, ibell requested changes

2023-11-28 01:58 UTC, ibell commented on src/CoolPropLib.cpp
> +    CoolProp::extract_backend(fluid_string, _backend, _fluid);
This function can throw I believe, so I think you need to refactor the code with error handling like the others.

2023-11-28 02:11 UTC, ibell commented on src/CoolPropLib.cpp
> +    CoolProp::extract_backend(fluid_string, _backend, _fluid);
Nevermind, it can't throw.

2023-11-28 02:12 UTC, ibell commented
I guess we can merge, right?

2023-11-28 10:15 UTC, merged